version: '2'
services:
    builder:
        build:
            context: .
            dockerfile: build.Dockerfile
        volumes:
            - ./:/var/www
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"