version: '2'
services:
    web:
        image: nginx:alpine
        volumes:
            - ./dist:/usr/share/nginx/html/dist
            - ./index.html:/usr/share/nginx/html/index.html
        ports:
            - "80:80"
